### ISSUE TITLE
error: AttributeError: module 'torch.cuda' has no attribute 'comm'

### ISSUE THREAD

**Issue by siva-wellnesys** [mkocabas/EpipolarPose#43]
hi i am getting this error , while running the demo.ipynb in google colab with my image. can you help me for this.

**Comment by GeLee-Q** [comment]
I meet the same problem, Do you solve it ?

**Comment by hustxxj** [comment]
add "import torch.cuda.comm" in file lib/core/integral_loss.py

**Comment by hustxxj** [comment]
> I meet the same problem, Do you solve it ?

add "import torch.cuda.comm" in file lib/core/integral_loss.py

**Comment by HyunJai** [comment]
> > I meet the same problem, Do you solve it ?
> 
> add "import torch.cuda.comm" in file lib/core/integral_loss.py

I add "import torch.cuda.comm"

But, It didn't working in file lib/core/integral_loss.py

**Comment by mkocabas** [comment]
Which pytorch version are you using? It should work with the latest v1.7.

**Comment by HyunJai** [comment]
In file lib/core/integral_loss.py

Chage below parts and then it will be working

```
accu_x = accu_x * torch.cuda.comm.broadcast(torch.arange(float(x_dim)), devices=[accu_x.device.index])[0]
accu_y = accu_y * torch.cuda.comm.broadcast(torch.arange(float(y_dim)), devices=[accu_y.device.index])[0]
accu_z = accu_z * torch.cuda.comm.broadcast(torch.arange(float(z_dim)), devices=[accu_z.device.index])[0]
```


```
device = torch.device('cuda')

accu_x = accu_x * torch.arange(float(x_dim)).to(device)
accu_y = accu_y * torch.arange(float(y_dim)).to(device)
accu_z = accu_z * torch.arange(float(z_dim)).to(device)
```

![image](https://user-images.githubusercontent.com/38063309/105429449-cda52700-5c94-11eb-8035-1eaecde74d77.png)
